### PR TITLE
Adding maintainers from INSPIRE team

### PR DESCRIPTION
**Pull request by kaplun**
* As discussed in several Invenio forums, here's an initial proposal
  for sharing maintainership of certain Invenio modules, also with
  the INSPIRE team.

Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
cc @david-caro @jacquerie

**Comment by david-caro** [comment]
👍 form me

**Comment by lnielsen** [comment]
Thanks Sam. I'm working on a maintainers guide that I'd like to ship first (this week or next) before updating the permissions. Naturally if there's any urgency, let me know and we figure out a solution.

**Comment by kaplun** [comment]
No particular urgency in this very moment, I believe. Was just to make explicit our candidature in a written way so that we don't forget them :+1:

**Pull request merged**
